services:
  
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: >-
      start-from-steps
      --init-projections
      --init-initial-data
      --masterkey "MasterkeyNeedsToHave32Characters"
      --tlsMode external

    environment:
      # database configuration
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable

      # For convenience, ZITADEL should not ask to change the initial admin users password.
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
    
      # In case something doesn't work as expected,
      # it can be handy to be able to read the access logs.
      ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: true

      # External configuration
      # Using an external domain other than localhost proofs, that the proxy configuration works.
      # If ZITADEL can't resolve a requests original host to this domain,
      # it will return a 404 Instance not found error.
      ZITADEL_EXTERNALDOMAIN: dani.genogra.com
      ZITADEL_EXTERNALPORT: 443
      ZITADEL_EXTERNALSECURE: true
      ZITADEL_TLS_ENABLED: false
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8082:8080'
    volumes:
      - zitadel-data:/zitadel-data
    

  db:
    restart: 'always'
    image: postgres:17-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - 'zitadel'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    volumes:
      - zitadel-db-data:/var/lib/postgresql/data

  server:
    build: ./nodeserver
    env_file:
      - ./nodeserver/.env
    ports:
      - "5005:3000"
    volumes:
      - ./nodeserver/src:/app/src
      - ./nodeserver/scripts:/app/scripts
      - ./nodeserver/logs/stdout.log:/app/logs/stdout.log
    networks:
      - zitadel

  
  client:
    build: ./reactclient
    env_file:
      - ./reactclient/.env
    ports:
      - "5006:3000"
    volumes:
      - ./reactclient/src:/app/src
      - ./reactclient/public:/app/public
      - ./reactclient/logs/stdout.log:/app/logs/stdout.log
      - ./reactclient/.env:/app/.env
      
    depends_on:
      - server
    networks:
      - zitadel

volumes:
  zitadel-db-data:
  zitadel-data:
  
networks:
  zitadel:
  
